### ISSUE TITLE
Not sure if services are still relevant in cqrs

### ISSUE THREAD

**Issue by paulvanbladel** [kamilmysliwiec/nest-cqrs-example#3]
Very nice sample and very nice, neat and consice cqrs implementation !

In the sample it is suggested that still controller - service pipeline is useful.

I think that the whole idea of cqrs is among others, to give the aggregate root a more central place in favor of attached services.

I would simply call directly the command from the controller and remove the service.

**Comment by kamilmysliwiec** [comment]
Fully agree. I just removed the redundant services layer. Thanks!
