### ISSUE TITLE
DDD approach in Nest CQRS

### ISSUE THREAD

**Issue by IgorSzymanski** [kamilmysliwiec/nest-cqrs-example#6]
Since events, commands and models related to the business logic are part of the domain layer, they should remain framework-agnostic, but most tools in this plugin are decorators that you apply to directly in the domain layer or classes that you need to extend. What would be the best approach to separate the domain layer and move the plugin's mechanics to the application/infrastructure layer?

**Comment by justinpenguin45** [comment]
Why did you close this? Did someone answer your question? I have the same question
